### ISSUE TITLE
403 Forbidden ubuntu-16.04.1-desktop-amd64.iso.torrent

### ISSUE THREAD

**Issue by spemberton** [ubuntudesign/www.ubuntu.com#1321] opened 2017-02-13 10:07 UTC
403 Forbidden 
You don't have permission to access /16.04/ubuntu-16.04.1-desktop-amd64.iso.torrent on this server.
http://releases.ubuntu.com/16.04/ubuntu-16.04.1-desktop-amd64.iso.torrent?_ga=1.224895770.1288824597.1486980244

---
*Reported from: https://www.ubuntu.com/download/alternative-downloads*

**Comment by pmahnke** [comment] 2017-02-14 09:20
duplicate of #1328

Thank you for filing this.

There is an issue with releases not removing the GET parameter.

I have filed a RT ticket with IS to look into this.

**Comment by pmahnke** [comment] 2017-02-15 20:09
We believe this has been fixed now.  Thanks for reporting.

**Closed by pmahnke** 2017-02-15 20:09 UTC
Labels: Duplicate
