### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by kevin45244** [ubuntudesign/www.ubuntu.com#1314] opened 2017-02-08 16:55 UTC
Link below in Reported..  Throwing 403 forbidden on all .torrent links.

---
*Reported from: https://www.ubuntu.com/download/alternative-downloads*

**Comment by pmahnke** [comment] 2017-02-14 09:21
duplicate of #1328

there is an issue with releases not removing the GET parameter

I have filed a RT ticket with IS to look into this

**Comment by pmahnke** [comment] 2017-02-15 20:09
We believe this has been fixed now.  Thanks for reporting.

**Closed by pmahnke** 2017-02-15 20:09 UTC
Labels: Duplicate
