### ISSUE TITLE
"Read instructions link" is dead

### ISSUE THREAD

**Issue by tomcallway** [ubuntudesign/www.ubuntu.com#1156] opened 2016-11-29 20:46 UTC
As title. The link to Install Openstack instructionsis dead. Needs updating

**Comment by deadlight** [comment] 2016-12-01 13:52
@tomcallway can you include a URL for whoever picks this one up, please?

**Comment by magdalena-mirowicz** [comment] 2016-12-02 10:54
more details in this bug: Page not found on www.ubuntu.com #1165

**Comment by magdalena-mirowicz** [comment] 2016-12-02 14:31
@tomcallway I'm closing it since we have more details in the duplicate of this bug: https://github.com/ubuntudesign/www.ubuntu.com/issues/1165

**Closed by magdalena-mirowicz** 2016-12-02 14:31 UTC
